name: rlvlmf_2
channels:
  - defaults
dependencies:
  - python=3.10
  - absl-py
  - pyparsing
  - pip
  - pip:
    - chardet  
    - termcolor
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - git+https://github.com/facebookresearch/hydra.git@0.11_branch
    - matplotlib
    - scikit-image
    - tqdm
    - moviepy
    - shapely
    - gym==0.25.2
    - ftfy 
    - regex 
    - git+https://github.com/openai/CLIP.git
    - salesforce-lavis
    - openai==2.6.0
    - google-generativeai
    - pyquaternion
    - pygame
    - pyflex
    - glfw==1.11.2
    - gymnasium==0.29.1
    - pandas==2.1.4
    - pyopengl==3.1.7
    - mujoco==3.1.1
    - pybind11==2.10.4
    - pybind11-global==2.10.4
    - cmake==3.26.4
    - torch==2.5.1+cu121
    - torchvision==0.20.1+cu121
    - torchaudio==2.5.1+cu121 
    - --extra-index-url https://download.pytorch.org/whl/cu121
    - git+https://github.com/huggingface/transformers
